<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Ingressos.Alocador-f45757b7-eccc-4222-a4c0-34634085fd58</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ingressos.Domain\Ingressos.Domain.csproj" />
    <ProjectReference Include="..\Ingressos.Contracts\Ingressos.Contracts.csproj" />
    <ProjectReference Include="..\Ingressos.Messaging\Ingressos.Messaging.csproj" />
    <ProjectReference Include="..\Ingressos.Persistence\Ingressos.Persistence.csproj" />
  </ItemGroup>
</Project>
